### ISSUE TITLE
InternalError exception when switching threads inside server implementation

### ISSUE THREAD

**Issue by ghostbuster91** [fiadliel/fs2-grpc#225]
```
io.grpc.StatusRuntimeException: INTERNAL: Calling TypedActor.context outside of a TypedActor implementation method!
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at org.lyranthe.fs2_grpc.java_runtime.client.Fs2UnaryClientCallListener.$anonfun$getValue$2(Fs2UnaryClientCallListener.scala:26)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:145)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.run(Callback.scala:131)
	at cats.effect.internals.Trampoline.cats$effect$internals$Trampoline$$immediateLoop(Trampoline.scala:67)
	at cats.effect.internals.Trampoline.startLoop(Trampoline.scala:35)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.super$startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.$anonfun$startLoop$1(TrampolineEC.scala:90)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at cats.effect.internals.TrampolineEC$JVMTrampoline.startLoop(TrampolineEC.scala:90)
	at cats.effect.internals.Trampoline.execute(Trampoline.scala:43)
	at cats.effect.internals.TrampolineEC.execute(TrampolineEC.scala:42)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:137)
	at cats.effect.internals.Callback$AsyncIdempotentCallback.apply(Callback.scala:126)
	at cats.effect.concurrent.Deferred$ConcurrentDeferred.$anonfun$unsafeRegister$1(Deferred.scala:204)
	at cats.effect.concurrent.Deferred$ConcurrentDeferred.$anonfun$unsafeRegister$1$adapted(Deferred.scala:204)
	at cats.effect.concurrent.Deferred$ConcurrentDeferred.$anonfun$notifyReadersLoop$1(Deferred.scala:239)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$RestartCallback.signal(IORunLoop.scala:366)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:387)
	at cats.effect.internals.IORunLoop$RestartCallback.apply(IORunLoop.scala:330)
	at cats.effect.internals.IOShift$Tick.run(IOShift.scala:36)
	at cats.effect.internals.PoolUtils$$anon$2$$anon$3.run(PoolUtils.scala:52)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Process finished with exit code 1

```

It is caused by calling `IO.fromFuture` which I assume cross threads boundaries. Following code in server implementation causes this error:

```
  override def getAccount(request: AccountRef, ctx: Metadata): IO[GrpcAccount] = {
    IO.fromFuture(IO.delay(Future(Account(1,"123",None,"cd"))))
  }
```
changing it to 
```
override def getAccount(request: AccountRef, ctx: Metadata): IO[GrpcAccount] = {
    IO.delay(Account(1,"123",None,"cd"))
  }
```
fixes the problem but that's not an option for us.

**Comment by ahjohannessen** [comment]
The following might be helpful: https://github.com/slouc/concurrency-in-scala-with-ce - look into `ContextShift`.

**Comment by ahjohannessen** [comment]
Seems to be an Akka thing, you might get better help by asking Akka dev, e.g. on Gitter or similar.

**Comment by ghostbuster91** [comment]
Hmm, I know the concept of `ContextShift` and I also agree that it seems to be some akka related problem since the error message contains something about `TypedActor`. Although, the code I showed you doesn't contain any actors. Moreover, the error is being thrown by `org.lyranthe.fs2_grpc.java_runtime.client.Fs2UnaryClientCallListener.$anonfun$getValue$2(Fs2UnaryClientCallListener.scala:26)` and AFAIK it should be fine to call `IO.fromFuture`. With all the respect, I really don't know how your messages could help me.
